version: '3.1'

services:
 db:
    container_name: todo-container
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: todoadmin
      POSTGRES_PASSWORD: todo123
      POSTGRES_DB: todo-list